import { TIMELINE_CANVAS_PAD } from "../layout/padding";

export { TIMELINE_CANVAS_PAD };
export const PAD = TIMELINE_CANVAS_PAD;

export const OVERLAY_LANE_HEIGHT = 16;
export const OVERLAY_LANE_GAP = 8;
export const OVERLAY_PANEL_GAP = 48;
// Keep breathing room beneath the parent, but avoid bottom padding so child rows
// can still snap to the same vertical rhythm as neighboring overlay lanes.
export const EXPANDED_OVERLAY_TOP_PADDING = OVERLAY_LANE_GAP;
export const EXPANDED_OVERLAY_BOTTOM_PADDING = 0;

export const CALENDAR_DAY_STEP = 1 / 365.2425;

export const PROJECT_LABEL_TOP = 10;
export const BREADCRUMB_TOP = 26;
export const BREADCRUMB_HEIGHT = 16;
export const BREADCRUMB_TO_OVERLAY_GAP = 8;
export const TIMELINE_BOTTOM_PADDING = 18;
export const COMPACT_TIMELINE_BOTTOM_PADDING_EXTRA = 24;
export const COMPACT_TIMELINE_BOTTOM_PADDING_MAX_HEIGHT = 560;
export const COMPACT_MARKER_STACK_MAX_HEIGHT = 430;
export const ROOMY_TIMELINE_BOTTOM_PADDING_START_HEIGHT = 640;
export const ROOMY_TIMELINE_BOTTOM_PADDING_MAX_EXTRA = 12;
export const AXIS_DATE_LABEL_HEIGHT = 11;
export const AXIS_YEAR_LABEL_HEIGHT = 11;
export const AXIS_LABEL_ROW_GAP = 2;
export const AXIS_MAJOR_TICK_TOP_OFFSET = 24;
export const AXIS_MAJOR_TICK_BOTTOM_OFFSET = 24;
export const AXIS_TICK_TO_LABEL_GAP = 8;
export const COMFORTABLE_AXIS_TO_MARKER_LABEL_GAP = 18;
export const COMPACT_AXIS_TO_MARKER_LABEL_GAP = 4;
export const MARKER_STEM_BOTTOM_OFFSET = 12;
export const MARKER_STEM_TO_LABEL_GAP = 4;
export const MARKER_LABEL_HEIGHT = 12;
export const COMFORTABLE_MARKER_LABEL_ROW_GAP = 4;
export const COMPACT_MARKER_LABEL_ROW_GAP = 1;
export const MARKER_DATE_HEIGHT = 10;
export const COMFORTABLE_MARKER_TO_AXIS_LABEL_GAP = 6;
export const COMPACT_MARKER_TO_AXIS_LABEL_GAP = 4;

export const AXIS_LABEL_OCCUPIED_PADDING = 28;
export const AXIS_LABEL_CLEARANCE_FADE_START = -14;
export const AXIS_LABEL_CLEARANCE_FADE_END = 40;
export const AXIS_DUPLICATE_LABEL_MIN_GAP = 18;
export const AXIS_TICK_ANIMATION_SMOOTHING_MS = 120;
export const AXIS_TICK_LABEL_FADE_IN_SMOOTHING_MS = 90;
export const AXIS_TICK_LABEL_FADE_OUT_SMOOTHING_MS = 185;
export const AXIS_TICK_OVERSCAN_PX = 160;
export const AXIS_LABEL_HYSTERESIS_KEEP_RATIO = 0.86;
export const AXIS_SUBYEAR_SECONDARY_STEP_RATIO = 0.7;
export const AXIS_LABEL_SECONDARY_STEP_RATIO = 0.82;
export const EDGE_AXIS_LABEL_SNAP_TOLERANCE_PX = 2;
export const SUBYEAR_EDGE_LABEL_MIN_SPACING_PX = 72;
export const SUBYEAR_LABEL_MIN_CLEARANCE_PX = 12;
export const subyearPrimaryFont = (fontSans: string) => `11px ${fontSans}`;
export const subyearSecondaryFont = (fontSans: string) => `10px ${fontSans}`;

export const ERA_CHILD_FADE_IN_DURATION_MS = 220;
export const ERA_CHILD_FADE_OUT_DURATION_MS = 160;
export const MARKER_PRIORITY_BOOST_SMOOTHING_MS = 130;
export const EXPANDED_OVERLAY_ANIMATION_SMOOTHING_MS = 170;
export const CONTEXT_BAND_LABEL_TRANSITION_DURATION_MS = 160;

export const OVERLAY_BAND_FADE_IN_SMOOTHING_MS = 80;
export const OVERLAY_BAND_FADE_OUT_SMOOTHING_MS = 50;
export const OVERLAY_BAND_POSITION_SMOOTHING_MS = 70;
export const OVERLAY_BAND_ENTER_SLIDE_PX = 5;
export const OVERLAY_BAND_EXIT_SLIDE_PX = 6;
export const OVERLAY_BAND_REFLOW_START_OPACITY = 0.85;

export const MIN_EXPANDED_OVERLAY_PARENT_WIDTH = 220;
export const EXPANDED_OVERLAY_CHROME_STEM_REVEAL_END = 0.18;
export const EXPANDED_OVERLAY_CHROME_RAIL_REVEAL_START = 0.1;
export const EXPANDED_OVERLAY_CHROME_RAIL_REVEAL_END = 0.32;
export const EXPANDED_OVERLAY_CHILD_REVEAL_START = 0.16;
export const EXPANDED_OVERLAY_CHILD_LANE_STAGGER = 0.1;
export const EXPANDED_OVERLAY_CHILD_REVEAL_DURATION = 0.52;
export const EXPANDED_OVERLAY_CHILD_SLIDE_PX = 8;
export const EXPANDED_OVERLAY_LABEL_REVEAL_DELAY = 0.18;
export const EXPANDED_OVERLAY_LABEL_REVEAL_DURATION = 0.28;
export const EXPANDED_OVERLAY_INTERACTION_REVEAL_THRESHOLD = 0.35;

export const ERA_BAND_ALPHA = 0.33;
export const OVERLAY_BAND_ALPHA = 1;
export const OVERLAY_BAND_SIDE_PADDING = 5;
export const OVERLAY_BAND_DISCLOSURE_RESERVED_WIDTH = 18;
export const OVERLAY_GROUP_ICON_PARENT_ALPHA = 0.44;
export const OVERLAY_GROUP_ICON_CHILD_ALPHA = 0.4;
export const EXPANDED_OVERLAY_CONNECTOR_ALPHA = 1;
export const EXPANDED_OVERLAY_CONNECTOR_LINE_WIDTH = 1;
export const EXPANDED_OVERLAY_CHILD_BORDER_ALPHA = 1;
export const PARENT_ERA_TINT_ALPHA = 0.05;
export const MIN_VISIBLE_OVERLAY_CHILD_WIDTH = 1;

export const TOOLTIP_OFFSET = 3;
export const TOOLTIP_MAX_WIDTH = 280;
export const TOOLTIP_BRIDGE_BASE_HALF_WIDTH = 16;
export const TOOLTIP_EXIT_DURATION_MS = 170;

export const CLICK_DRAG_THRESHOLD = 6;
export const VIEWPORT_INTERACTION_SETTLE_MS = 120;

export const canExpandOverlayParent = (bandWidth: number, childCount: number) =>
  childCount > 0 && bandWidth >= MIN_EXPANDED_OVERLAY_PARENT_WIDTH;
