import type { TimelineMarker } from "../../core/timelineTypes";
import { bce, ce } from "../timelineDateBuilders";

const PHYSICS_OF_UNIVERSE_SOURCE_IDS = ["physicsOfUniverseDates"];
const WIKIPEDIA_TIMELINE_SOURCE_IDS = [
  "timelineOfFundamentalPhysicsDiscoveriesWikipedia",
];

export const PHYSICS_HISTORY_MARKERS: TimelineMarker[] = [
  {
    id: "physics-babylonian-planetary-records",
    label: "Babylonian skywatchers distinguish planets from stars",
    shortLabel: "Babylonian Planets",
    year: bce(1_800),
    dateLabel: "20th-16th century BCE",
    approximate: true,
    minZoom: 13,
    priority: 82,
    description:
      "Ancient Babylonian tablets track regular planetary motion and separate wandering planets from fixed stars.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-rigveda-cosmic-egg",
    label: "Rigveda describes a cosmic egg universe",
    shortLabel: "Cosmic Egg",
    year: bce(1_350),
    dateLabel: "15th-12th century BCE",
    approximate: true,
    minZoom: 13,
    priority: 80,
    description:
      "The Rigveda describes a universe emerging from a concentrated cosmic egg, a striking early cosmological image.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-thales-natural-philosophy",
    label: "Thales introduces natural philosophy",
    shortLabel: "Thales",
    year: bce(585),
    dateLabel: "7th-6th century BCE",
    approximate: true,
    minZoom: 14,
    priority: 83,
    description:
      "Thales helps shift explanation of the physical world toward natural causes instead of mythic ones.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-anaximander-earth-in-space",
    label: "Anaximander imagines Earth suspended in space",
    shortLabel: "Anaximander",
    year: bce(560),
    dateLabel: "7th-6th century BCE",
    approximate: true,
    minZoom: 14,
    priority: 82,
    description:
      "Anaximander treats Earth as a body floating in space rather than resting on a physical support.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-anaxagoras-rational-matter",
    label: "Anaxagoras treats matter as a rational physical system",
    shortLabel: "Anaxagoras",
    year: bce(450),
    dateLabel: "5th century BCE",
    approximate: true,
    minZoom: 14,
    priority: 84,
    description:
      "Anaxagoras treats the universe as matter governed by intelligible order rather than divine whim.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-greek-atomism",
    label: "Greek atomism takes shape",
    shortLabel: "Greek Atomism",
    year: bce(430),
    dateLabel: "5th century BCE",
    approximate: true,
    minZoom: 14,
    priority: 88,
    description:
      "Leucippus and Democritus argue that the universe is built from tiny, indivisible atoms moving in an infinite void.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-aristotle-geocentric-cosmos",
    label: "Aristotle describes a geocentric cosmos",
    shortLabel: "Aristotle's Cosmos",
    year: bce(350),
    dateLabel: "4th century BCE",
    approximate: true,
    minZoom: 14,
    priority: 87,
    description:
      "Aristotle describes a finite, eternal geocentric universe of concentric celestial spheres around a stationary Earth.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-heraclides-rotating-earth",
    label: "Heraclides explains daily motion with a rotating Earth",
    shortLabel: "Heraclides",
    year: bce(350),
    dateLabel: "4th century BCE",
    approximate: true,
    minZoom: 14,
    priority: 85,
    description:
      "Heraclides explains the daily motion of the stars by having Earth turn on its axis.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-eratosthenes-earth-circumference",
    label: "Eratosthenes measures Earth's circumference",
    shortLabel: "Earth Measured",
    year: bce(240),
    dateLabel: "3rd century BCE",
    approximate: true,
    minZoom: 14,
    priority: 86,
    description:
      "Eratosthenes shows that Earth is round and calculates its circumference with remarkable accuracy.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-aristarchus-heliocentrism",
    label: "Aristarchus argues for heliocentrism",
    shortLabel: "Aristarchus",
    year: bce(280),
    dateLabel: "3rd century BCE",
    approximate: true,
    minZoom: 14,
    priority: 85,
    description:
      "Aristarchus presents the first explicit case for placing the Sun, not Earth, at the center of the known universe.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-archimedes-principle",
    label: "Archimedes formulates buoyancy",
    shortLabel: "Archimedes",
    year: bce(250),
    dateLabel: "c. 250 BCE",
    approximate: true,
    minZoom: 14,
    priority: 84,
    description:
      "Archimedes gives physics one of its classic quantitative results with the principle of buoyancy.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-hipparchus-precession",
    label: "Hipparchus catalogs the sky and measures precession",
    shortLabel: "Hipparchus",
    year: bce(129),
    dateLabel: "2nd century BCE",
    approximate: true,
    minZoom: 14,
    priority: 84,
    description:
      "Hipparchus compiles a star catalog and identifies the precession of the equinoxes.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-ptolemaic-model",
    label: "Ptolemy standardizes geocentric astronomy",
    shortLabel: "Ptolemy",
    year: ce(150),
    dateLabel: "2nd century CE",
    approximate: true,
    minZoom: 14,
    priority: 84,
    description:
      "Ptolemy's geocentric system of circles and epicycles becomes scientific orthodoxy for nearly two millennia.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-aryabhata-rotating-earth",
    label: "Aryabhata proposes a rotating Earth",
    shortLabel: "Aryabhata",
    year: ce(500),
    dateLabel: "5th century CE",
    approximate: true,
    minZoom: 14,
    priority: 83,
    description:
      "Aryabhata proposes that Earth turns on its axis, shifting the apparent motion of the heavens.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-john-philoponus-impetus",
    label: "John Philoponus develops impetus theory",
    shortLabel: "Impetus Theory",
    year: ce(500),
    dateLabel: "5th century CE",
    approximate: true,
    minZoom: 14,
    priority: 82,
    description:
      "John Philoponus challenges old motion theory with an early account of impetus.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-brahmagupta-gravity",
    label: "Brahmagupta describes gravity as attraction",
    shortLabel: "Brahmagupta",
    year: ce(628),
    minZoom: 14,
    priority: 82,
    description:
      "Brahmagupta describes gravity as a force of attraction between the Sun and Earth.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-ibn-sahl-refraction",
    label: "Ibn Sahl states the law of refraction",
    shortLabel: "Ibn Sahl",
    year: ce(984),
    minZoom: 15,
    priority: 83,
    description:
      "Ibn Sahl gives an early mathematical law of refraction centuries before Snell's famous restatement.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-alhazen-scientific-method",
    label: "Alhazen transforms optics and method",
    shortLabel: "Alhazen",
    year: ce(1010),
    dateLabel: "c. 1010",
    approximate: true,
    minZoom: 15,
    priority: 84,
    description:
      "Alhazen reshapes optics and treats observation, experiment, and proof as partners in physical inquiry.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-al-biruni-gravitation",
    label: "Al-Biruni links gravity to Earth's center",
    shortLabel: "Al-Biruni",
    year: ce(1050),
    dateLabel: "11th century",
    approximate: true,
    minZoom: 15,
    priority: 82,
    description:
      "Al-Biruni describes gravitation as the tendency of things toward Earth's center and entertains Earth's motion.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-copernicus-heliocentrism",
    label: "Copernicus revives heliocentrism",
    shortLabel: "Copernicus",
    year: ce(1543),
    minZoom: 15,
    priority: 90,
    description:
      "Copernicus argues that Earth rotates daily and travels around the Sun once a year.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-tycho-hybrid-cosmos",
    label: "Tycho Brahe builds a geo-heliocentric compromise",
    shortLabel: "Tychonic System",
    year: ce(1587),
    minZoom: 15,
    priority: 79,
    description:
      "Tycho Brahe proposes a hybrid system with a fixed Earth, orbiting Sun and Moon, and planets circling the Sun.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-kepler-laws",
    label: "Kepler's laws of planetary motion",
    shortLabel: "Kepler's Laws",
    year: ce(1605),
    minZoom: 15,
    priority: 89,
    description:
      "Kepler makes planetary motion mathematical and replaces perfect circles with ellipses.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-galileo-telescope",
    label: "Galileo's telescope strengthens heliocentrism",
    shortLabel: "Galileo's Telescope",
    year: ce(1610),
    minZoom: 15,
    priority: 88,
    description:
      "Galileo's telescope reveals Jupiter's moons, sunspots, and Venus's phases, strengthening the Copernican model.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-galilean-relativity",
    label: "Galileo states the principle of relativity",
    shortLabel: "Galilean Relativity",
    year: ce(1632),
    minZoom: 15,
    priority: 87,
    description:
      "Galileo states that the fundamental laws of physics are the same in all inertial frames.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-galileo-free-fall",
    label: "Galileo shows falling bodies share one acceleration",
    shortLabel: "Free Fall",
    year: ce(1638),
    minZoom: 15,
    priority: 86,
    description:
      "Galileo shows that freely falling bodies share the same constant acceleration in a vacuum.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-romer-speed-of-light",
    label: "Rømer estimates the speed of light",
    shortLabel: "Rømer",
    year: ce(1676),
    minZoom: 15,
    priority: 84,
    description:
      "Ole Rømer uses Jupiter's moons to show that light travels at a finite speed.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-newton-principia",
    label: "Newton publishes Principia",
    shortLabel: "Newton's Principia",
    year: ce(1687),
    minZoom: 15,
    priority: 96,
    description:
      "Newton unites terrestrial and celestial motion with the laws of motion and universal gravitation.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-bernoulli-kinetic-gases",
    label: "Bernoulli models gases as particles in motion",
    shortLabel: "Kinetic Gases",
    year: ce(1738),
    minZoom: 16,
    priority: 80,
    description:
      "Daniel Bernoulli gives the first recognizable kinetic theory of gases.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-michell-dark-stars",
    label: "Michell imagines dark stars",
    shortLabel: "Dark Stars",
    year: ce(1783),
    minZoom: 16,
    priority: 78,
    description:
      "John Michell proposes an object so massive that even light could not escape, an early black-hole idea.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-coulomb-law",
    label: "Coulomb confirms the inverse-square law for charge",
    shortLabel: "Coulomb's Law",
    year: ce(1785),
    minZoom: 16,
    priority: 81,
    description:
      "Coulomb shows electric force follows an inverse-square law, making electrostatics quantitative.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-lavoisier-conservation-of-mass",
    label: "Lavoisier states conservation of mass",
    shortLabel: "Mass Conserved",
    year: ce(1789),
    minZoom: 16,
    priority: 82,
    description:
      "Lavoisier states the law of conservation of mass and treats elements as substances that cannot be broken into simpler ones.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-voltaic-pile",
    label: "Volta invents the voltaic pile",
    shortLabel: "Voltaic Pile",
    year: ce(1800),
    minZoom: 16,
    priority: 82,
    description:
      "Volta's battery gives physicists a steady artificial source of electric current.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-young-double-slit",
    label: "Young's double-slit experiment",
    shortLabel: "Double Slit",
    year: ce(1803),
    minZoom: 16,
    priority: 84,
    description:
      "Young shows light interference in the double-slit experiment and makes the wave theory of light hard to ignore.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-dalton-atomic-theory",
    label: "Dalton develops atomic theory",
    shortLabel: "Atomic Theory",
    year: ce(1805),
    minZoom: 16,
    priority: 83,
    description:
      "Dalton proposes that each chemical element is composed of atoms of a single unique type.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-fourier-heat-equation",
    label: "Fourier writes the heat equation",
    shortLabel: "Heat Equation",
    year: ce(1822),
    minZoom: 16,
    priority: 80,
    description:
      "Fourier turns heat flow into a mathematical field problem with the heat equation.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-faraday-induction",
    label: "Faraday discovers electromagnetic induction",
    shortLabel: "Induction",
    year: ce(1831),
    minZoom: 16,
    priority: 87,
    description:
      "Faraday shows changing magnetic fields can generate electric current.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-faraday-electromagnetism-light",
    label: "Faraday links electromagnetism and light",
    shortLabel: "Faraday",
    year: ce(1839),
    minZoom: 16,
    priority: 86,
    description:
      "Faraday argues that electricity, magnetism, and light are linked rather than separate phenomena.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-conservation-of-energy",
    label: "Conservation of energy takes modern form",
    shortLabel: "Energy Conserved",
    year: ce(1842),
    minZoom: 16,
    priority: 83,
    description:
      "Kelvin and Mayer help establish conservation of energy as a general physical principle.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-maxwell-electromagnetism",
    label: "Maxwell unifies electromagnetism",
    shortLabel: "Maxwell",
    year: ce(1864),
    minZoom: 16,
    priority: 92,
    description:
      "Maxwell shows that electric and magnetic fields travel as waves at the speed of light, identifying light as electromagnetic.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-michelson-morley",
    label: "Michelson and Morley fail to find the ether wind",
    shortLabel: "Michelson-Morley",
    year: ce(1887),
    minZoom: 16,
    priority: 86,
    description:
      "The Michelson-Morley experiment undermines the ether picture and sharpens the road toward relativity.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-roentgen-x-rays",
    label: "Röntgen discovers X-rays",
    shortLabel: "X-rays",
    year: ce(1895),
    minZoom: 16,
    priority: 86,
    description:
      "Röntgen reveals a penetrating new form of radiation and opens a new experimental window into matter.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-becquerel-radioactivity",
    label: "Becquerel discovers radioactivity",
    shortLabel: "Radioactivity",
    year: ce(1896),
    minZoom: 16,
    priority: 85,
    description:
      "Becquerel discovers that certain kinds of matter emit radiation of their own accord.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-thomson-electron",
    label: "J. J. Thomson discovers the electron",
    shortLabel: "Electron",
    year: ce(1897),
    minZoom: 16,
    priority: 90,
    description:
      "J. J. Thomson identifies the electron, the first known subatomic particle.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-planck-quanta",
    label: "Planck introduces energy quanta",
    shortLabel: "Planck Quanta",
    year: ce(1900),
    minZoom: 18,
    priority: 95,
    description:
      "Planck explains black-body radiation by proposing that light is emitted in discrete quanta.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-einstein-photoelectric-effect",
    label: "Einstein explains the photoelectric effect",
    shortLabel: "Photoelectric Effect",
    year: ce(1905),
    minZoom: 18,
    priority: 91,
    description:
      "Einstein explains the photoelectric effect through light quanta, pushing the quantum picture of light forward.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-einstein-special-relativity",
    label: "Einstein publishes special relativity",
    shortLabel: "Special Relativity",
    year: ce(1905),
    minZoom: 18,
    priority: 94,
    description:
      "Einstein extends relativity to all laws of physics and makes the speed of light constant for every inertial observer.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-minkowski-spacetime",
    label: "Minkowski recasts relativity as space-time",
    shortLabel: "Space-Time",
    year: ce(1907),
    minZoom: 18,
    priority: 86,
    description:
      "Minkowski shows that special relativity is best understood in four-dimensional space-time.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-rutherford-planetary-atom",
    label: "Rutherford's planetary atom",
    shortLabel: "Atomic Nucleus",
    year: ce(1911),
    minZoom: 18,
    priority: 90,
    description:
      "Rutherford interprets scattering experiments as an atom with a tiny central nucleus orbited by electrons.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-bohr-atom",
    label: "Bohr quantizes the atom",
    shortLabel: "Bohr Model",
    year: ce(1913),
    minZoom: 18,
    priority: 89,
    description:
      "Bohr gives the atom stable quantized orbits, helping quantum ideas stick to physical structure.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-noether-theorem",
    label: "Noether links symmetry to conservation",
    shortLabel: "Noether's Theorem",
    year: ce(1915),
    minZoom: 18,
    priority: 88,
    description:
      "Noether shows that physical symmetries generate conservation laws, a deep organizing principle of modern physics.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-einstein-general-relativity",
    label: "Einstein publishes general relativity",
    shortLabel: "General Relativity",
    year: ce(1916),
    minZoom: 18,
    priority: 95,
    description:
      "Einstein describes gravity as warped space-time, joining special relativity and gravitation in one theory.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-rutherford-proton",
    label: "Rutherford identifies the proton",
    shortLabel: "Proton",
    year: ce(1919),
    minZoom: 18,
    priority: 87,
    description:
      "Rutherford identifies the hydrogen nucleus as a fundamental positive particle, later named the proton.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-eddington-light-bending",
    label: "Eddington confirms light bending",
    shortLabel: "Light Bending",
    year: ce(1919),
    minZoom: 18,
    priority: 87,
    description:
      "Eddington's eclipse observations confirm the deflection of starlight predicted by general relativity.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-friedmann-expanding-universe",
    label: "Friedmann finds expanding-universe solutions",
    shortLabel: "Expanding Universe",
    year: ce(1922),
    minZoom: 18,
    priority: 86,
    description:
      "Friedmann finds expanding-universe solutions to Einstein's field equations.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-hubble-galaxies",
    label: "Hubble shows spiral nebulae are galaxies",
    shortLabel: "Other Galaxies",
    year: ce(1925),
    minZoom: 18,
    priority: 86,
    description:
      "Hubble shows spiral nebulae sit far beyond the Milky Way and are galaxies in their own right.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-pauli-exclusion-principle",
    label: "Pauli states the exclusion principle",
    shortLabel: "Exclusion Principle",
    year: ce(1925),
    minZoom: 18,
    priority: 85,
    description:
      "Pauli states that no two identical fermions may occupy the same quantum state.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-heisenberg-uncertainty-principle",
    label: "Heisenberg formulates uncertainty",
    shortLabel: "Uncertainty",
    year: ce(1926),
    minZoom: 18,
    priority: 93,
    description:
      "Heisenberg shows that certain pairs of quantities cannot both be known exactly at the same time.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-schrodinger-equation",
    label: "Schrödinger publishes his wave equation",
    shortLabel: "Schrödinger Eq.",
    year: ce(1926),
    minZoom: 18,
    priority: 92,
    description:
      "Schrödinger publishes the equation that becomes central to quantum physics.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-lemaitre-big-bang",
    label: "Lemaître sketches the Big Bang idea",
    shortLabel: "Lemaître",
    year: ce(1927),
    minZoom: 18,
    priority: 89,
    description:
      "Lemaître proposes an expanding universe and lays out the first definitive version of what becomes the Big Bang theory.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-dirac-antimatter",
    label: "Dirac predicts antimatter",
    shortLabel: "Antimatter",
    year: ce(1928),
    minZoom: 18,
    priority: 88,
    description:
      "Dirac gives a relativistic account of particle spin and predicts the existence of antimatter.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-hubble-law",
    label: "Hubble confirms the universe is expanding",
    shortLabel: "Hubble Law",
    year: ce(1929),
    minZoom: 18,
    priority: 90,
    description:
      "Hubble shows galaxies recede according to distance, turning expansion into an observational fact.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-neutron-and-positron",
    label: "Neutron and positron enter the picture",
    shortLabel: "Neutron & Positron",
    year: ce(1932),
    minZoom: 18,
    priority: 87,
    description:
      "Chadwick discovers the neutron, Anderson identifies the positron, and accelerator work starts splitting atoms deliberately.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-zwicky-dark-matter",
    label: "Zwicky infers dark matter",
    shortLabel: "Dark Matter",
    year: ce(1934),
    minZoom: 18,
    priority: 84,
    description:
      "Zwicky infers unseen matter from galaxy-cluster dynamics and points to gravitational lensing.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-chandrasekhar-limit",
    label: "Chandrasekhar sets the white-dwarf limit",
    shortLabel: "Chandrasekhar Limit",
    year: ce(1935),
    minZoom: 18,
    priority: 83,
    description:
      "Chandrasekhar defines the mass limit beyond which a collapsing star cannot remain a white dwarf.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-nuclear-fission",
    label: "Nuclear fission is discovered",
    shortLabel: "Nuclear Fission",
    year: ce(1939),
    minZoom: 18,
    priority: 91,
    description: "Experiments in Berlin reveal nuclear fission.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-quantum-electrodynamics",
    label: "Quantum electrodynamics takes modern shape",
    shortLabel: "QED",
    year: ce(1948),
    minZoom: 19,
    priority: 88,
    description:
      "Feynman, Schwinger, Tomonaga, and Dyson give quantum electrodynamics its precise modern form.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-kerr-black-hole",
    label: "Kerr solves the spinning black hole",
    shortLabel: "Kerr Solution",
    year: ce(1963),
    minZoom: 19,
    priority: 82,
    description:
      "Roy Kerr finds the exact space-time solution for a spinning black hole.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-quarks-predicted",
    label: "Quarks are proposed",
    shortLabel: "Quarks",
    year: ce(1963),
    minZoom: 19,
    priority: 87,
    description:
      "Gell-Mann and Zweig propose quarks as the building blocks behind hadron patterns.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-cosmic-microwave-background",
    label: "Cosmic microwave background detected",
    shortLabel: "CMB Detected",
    year: ce(1965),
    minZoom: 19,
    priority: 90,
    description:
      "Penzias and Wilson detect the cosmic microwave background, the strongest evidence yet for the Big Bang.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-electroweak-unification",
    label: "Electroweak theory unifies two forces",
    shortLabel: "Electroweak",
    year: ce(1967),
    minZoom: 19,
    priority: 86,
    description:
      "Electromagnetism and the weak interaction are brought into one electroweak framework.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-quarks-confirmed",
    label: "Experiments find evidence for quarks",
    shortLabel: "Quark Evidence",
    year: ce(1968),
    minZoom: 19,
    priority: 86,
    description:
      "Deep inelastic scattering gives strong experimental evidence that quarks are physically real.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-hawking-radiation",
    label: "Hawking predicts black holes radiate",
    shortLabel: "Hawking Radiation",
    year: ce(1974),
    minZoom: 19,
    priority: 88,
    description:
      "Hawking shows black holes should emit radiation, tying gravity, thermodynamics, and quantum theory together.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-inflation-proposed",
    label: "Inflation is proposed",
    shortLabel: "Inflation",
    year: ce(1980),
    minZoom: 19,
    priority: 85,
    description:
      "Guth proposes a brief burst of exponential inflation to solve the horizon and flatness problems of the standard Big Bang model.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-w-and-z-bosons",
    label: "W and Z bosons are directly observed",
    shortLabel: "W & Z",
    year: ce(1984),
    minZoom: 19,
    priority: 87,
    description:
      "Experiments directly observe the W and Z bosons, a major win for electroweak theory.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-bose-einstein-condensate",
    label: "Bose-Einstein condensate is observed",
    shortLabel: "BEC",
    year: ce(1995),
    minZoom: 19,
    priority: 84,
    description:
      "Physicists produce a Bose-Einstein condensate in the lab, revealing a quantum state on macroscopic scales.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-accelerating-universe",
    label: "Accelerating cosmic expansion is found",
    shortLabel: "Accelerating Universe",
    year: ce(1998),
    minZoom: 19,
    priority: 86,
    description:
      "Observations of distant Type Ia supernovas show that the expansion of the universe is accelerating.",
    sourceIds: PHYSICS_OF_UNIVERSE_SOURCE_IDS,
  },
  {
    id: "physics-quark-gluon-plasma",
    label: "Quark-gluon plasma is created",
    shortLabel: "QGP",
    year: ce(2000),
    minZoom: 20,
    priority: 84,
    description:
      "Experiments create quark-gluon plasma, recreating matter closer to the early universe's first moments.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-graphene-properties",
    label: "Graphene's exceptional properties are identified",
    shortLabel: "Graphene",
    year: ce(2004),
    minZoom: 20,
    priority: 81,
    description:
      "Experiments reveal graphene as a two-dimensional material with striking quantum and electronic behavior.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-higgs-boson-found",
    label: "Experiments find a Higgs-like boson",
    shortLabel: "Higgs Boson",
    year: ce(2012),
    dateLabel: "Jul 4, 2012",
    minZoom: 20,
    priority: 92,
    description:
      "A new particle is discovered with properties matching the predicted Higgs boson.",
    sourceIds: ["cernHiggsBoson2012"],
  },
  {
    id: "physics-gravitational-waves-observed",
    label: "Gravitational waves are observed",
    shortLabel: "Gravitational Waves",
    year: ce(2015),
    minZoom: 20,
    priority: 91,
    description:
      "Physicists make the first direct observation of gravitational waves.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-first-black-hole-image",
    label: "First image of a black hole released",
    shortLabel: "Black Hole Image",
    year: ce(2019),
    minZoom: 20,
    priority: 90,
    description: "The first image of a black hole is released.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
  {
    id: "physics-gravitational-wave-background",
    label: "Evidence appears for a gravitational-wave background",
    shortLabel: "GW Background",
    year: ce(2023),
    minZoom: 20,
    priority: 84,
    description:
      "Pulsar timing arrays report evidence for a stochastic gravitational-wave background across the sky.",
    sourceIds: WIKIPEDIA_TIMELINE_SOURCE_IDS,
  },
];
