export const DUAL_EDGE_CENTER_ZOOM_DELTA_PER_PIXEL = 0.01;
export const TOUCH_CLICK_DRAG_THRESHOLD = 12;
export const TOUCH_TOOLTIP_HIT_SLOP_PX = 28;
export const OVERLAY_SCROLL_TOUCH_THRESHOLD_PX = 8;
