import { STATIC_TIMELINE_CATALOG } from "./timelineCatalog";

export const TIMELINE_SETS = STATIC_TIMELINE_CATALOG.sets;
export const TIMELINE_SETS_BY_ID = STATIC_TIMELINE_CATALOG.setsById;
export const TIMELINE_DECORATION_CATEGORIES = STATIC_TIMELINE_CATALOG.categories;
export const TIMELINE_DECORATION_GROUPS = STATIC_TIMELINE_CATALOG.groups;
export const TIMELINE_DECORATION_GROUPS_BY_ID =
  STATIC_TIMELINE_CATALOG.groupsById;
export const TIMELINE_MARKERS = STATIC_TIMELINE_CATALOG.markers;
export const TIMELINE_OVERLAYS = STATIC_TIMELINE_CATALOG.overlays;
export const TIMELINE_DISPLAY = STATIC_TIMELINE_CATALOG.display;
export const TIMELINE_SOURCES_BY_ID = STATIC_TIMELINE_CATALOG.sourcesById;
export const TIMELINE_SET_ID_BY_FAMILY_ID =
  STATIC_TIMELINE_CATALOG.setIdByFamilyId;
export const TIMELINE_SET_ID_BY_GROUP_ID = STATIC_TIMELINE_CATALOG.setIdByGroupId;
export const TIMELINE_OVERLAY_LANE_BIAS_YEARS =
  STATIC_TIMELINE_CATALOG.overlayLaneBiasById;
export const TIMELINE_SET_SPAN_PRIORITY_BY_ID =
  STATIC_TIMELINE_CATALOG.setSpanPriorityById;
